function imageUrlToBase64(url, callback) {
    fetch(url, {
        method: 'GET',
        mode: 'cors'
    })
    .then(response => {
        if (!response.ok) {
            throw new Error('Network response was not ok');
        }
        return response.blob();
    })
    .then(blob => {
        const reader = new FileReader();
        reader.readAsDataURL(blob);
        reader.onloadend = () => {
            const base64data = reader.result;
            callback(base64data);
        };
    })
    .catch(error => {
        console.error('Error fetching or encoding image:', error);
        callback(null);
    });
}




const fileName = "db.json";

console.log(fileName);
const main = document.getElementById("dynamic-part");
// main.style.backgroundColor = "#E8FC00"


fetch(fileName) 
  .then(response => response.json()) 
  .then(data => {
      Display(data);
      mobile(data);
  })
  .catch(error => console.error('Error fetching data:', error));

// ------------------------------------Download button------------->>>>>
document.getElementById("download-btn");

function generatePdfWithJSPDF() {
    const ele = document.getElementById("pdf");
    // const options = {
    // //   margin: 10, 
    //   filename: 'pdf_file.pdf', 
    //   image: { type: 'jpeg', quality: 0.98 }, 
    //   html2canvas: { scale: 1 }, 
    //   jsPDF: { unit: 'pt',  format: 'a4', orientation: 'portrait' }
    // //   jsPDF: { unit: 'px', format: [1024, 800], orientation: 'portrait' }
    // };
    const options = {
        margin: [10, 10, 10, 10], // Top, Left, Bottom, Right margin in mm
        filename: 'pdf_file.pdf',
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, logging: true, dpi: 192, letterRendering: true },
        // jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
        jsPDF: { unit: 'pt',  format: 'a4', orientation: 'portrait' }
    };
    html2pdf()
      .set(options)
      .from(ele) 
      .save();
  }


  function generateFooter() {
    // Create elements
    let footerContainer = document.createElement('div');
    let innerContainer = document.createElement('div');
    let generatedByText = document.createElement('p');
    let logoImage = document.createElement('img');
    
    // Set attributes, styles, and text content for each element
    footerContainer.className = 'footer-mudcy';
    footerContainer.setAttribute('style', `
        display: flex;
        justify-content: flex-end;
        border: 2px solid;
        border-top: none;
        border-bottom: none;
        border-left: none;
        border-right: none;
        background-color: #e8fc00;`);
        
    innerContainer.setAttribute('style', `
        display: flex;
        align-items: center;
        height:40px`);
        
    generatedByText.innerHTML = 'Generated by';
    generatedByText.setAttribute('style', `
        margin-right: 10px;
        margin-top: 25px;`);
        
    logoImage.src = './assets/muducy-logo.png';
    logoImage.alt = 'Error in Muducy';
    logoImage.setAttribute('style', `
        height: 40px;
        width: auto;`);
    
    // Append child nodes to parent containers
    innerContainer.append(generatedByText, logoImage);
    footerContainer.append(innerContainer);

    return footerContainer;
}


// -------------Function for mobile -------


function mobile(data){
    const divMobile = document.createElement("div")
    divMobile.classList.add("Mobile-div"); 
    // data.forEach(ele => {
        for(let i=0;i<data.Mobile.length;i++){
            const ele = data.Mobile[i]
            console.log("Mobile-ele",ele)
        const urlMob = ele["image_url"];
        // const croFeedbackMob = data[`cro_feedback_mob-${i}`];
        
        const divMobileImage = document.createElement("div")
        divMobileImage.classList.add("Mobile-div-image"); 


        const mobileImageTag = document.createElement("img")
        imageUrlToBase64(urlMob, base64data => {
                if (base64data) {
                    // console.log(base64data)
                    mobileImageTag.src = base64data
                } else {
                    console.log('Failed to fetch and encode image.');
                }
            });
        mobileImageTag.alt = "error in mobile image"; 
        divMobileImage.append(mobileImageTag)

        
        const mobileDesc = document.createElement("div")
        mobileDesc.classList.add("Mobile-div-desc"); 

        
        const h3TagMob = document.createElement("h3")
        h3TagMob.textContent = "1.Hey i am first for Mobile"
        const pTagMob = document.createElement("p")
        pTagMob.textContent = `feedback`

        mobileDesc.append(h3TagMob,pTagMob)
        divMobile.append(divMobileImage,mobileDesc)
    };
        return divMobile

}


  
function Display(data){
    // data = JSON.parse(data.Desktop)
    // console.log("data",data.Desktop)
    for (let i =0; i <data.Desktop.length; i++) {

        const mainChild = document.createElement("div")
mainChild.style.backgroundColor = "#E8FC00";
mainChild.style.marginTop = "50px";
mainChild.style.border = "2px solid black";
mainChild.style.height = "1060px";

        // const deviceTypeMob = data[`device_type_des-${i}`];
        const urlDes = data.Desktop[i]["image_url"];
        // console.log("desktop",urlDes)
        const croFeedbackDes = data[`cro_feedback_des-${i}`];

        const DesktopDiv = document.createElement("div");
        // DesktopDiv.style.border = "5px solid teal";
        const header = document.createElement("div");
        header.classList.add("main-heading");
        // header.style.backgroundColor = "#E8FC00";
        const h2Tag = document.createElement("h2");
        h2Tag.textContent = `${i+1}. ${data.Desktop[i]["main_heading"]}`;
        header.appendChild(h2Tag);
        
  
        const headerImageDiv = document.createElement("div");
        headerImageDiv.classList.add("mainbanner-div");
        const imgTag = document.createElement("img");
        // imgTag.src = urlDes;
        imageUrlToBase64(urlDes, base64data => {
            if (base64data) {
                // console.log("base64",base64data)
                imgTag.src =base64data
                // imgTag.src =`data:image/jpeg;base64,/${base64data}`
            } else {
                console.log('Failed to fetch and encode image.');
            }
        });
          
        imgTag.alt = "error in image1";
        headerImageDiv.appendChild(imgTag);
        
        const desktopDesc = document.createElement("div");
        desktopDesc.classList.add("desktopDesc-div");
        // const ptaghead = document.createElement("p");
        
// Inside your JavaScript loop where you create each desktopDesc
data.Desktop[i].array.forEach((sectionObj, index) => {
    Object.values(sectionObj).forEach((sectionArr) => {
      sectionArr.forEach((section) => {
        const pTag = document.createElement("p");
        pTag.classList.add("advice");
  
        // Create the span for the index number
        const spanIndex = document.createElement("span");
        spanIndex.textContent = `${index + 1}. `;
        spanIndex.classList.add("index-number");
  
        // Create the span for the heading text
        const spanHeading = document.createElement("span");
        spanHeading.textContent = section.advice_heading + ": ";
        spanHeading.classList.add("advice-heading");
  
        // Create the span for the advice text
        const spanAdvice = document.createElement("span");
        spanAdvice.textContent = section.advice;
        spanAdvice.classList.add("advice-text");
  
        // Append the spans to the pTag
        pTag.appendChild(spanIndex);
        pTag.appendChild(spanHeading);
        pTag.appendChild(spanAdvice);
  
        // Append the pTag to the desktopDesc
        desktopDesc.appendChild(pTag);
      });
    });
  });

 DesktopDiv.append(header,headerImageDiv,desktopDesc);


// Mobile
// for(let j=0;j<data.Mobile.length;j++){
//     console.log("j",j)
// }

        



// const footerContainer = document.createElement("div");
// footerContainer.classList.add("footer-mudcy");
// footerContainer.style.display = "flex";
// footerContainer.style.justifyContent = "flex-end";
// footerContainer.style.border = "2px solid";
// footerContainer.style.borderTop = "none";
// footerContainer.style.borderBottom = "none";
// footerContainer.style.borderLeft = "none";
// footerContainer.style.borderRight = "none";
// footerContainer.style.backgroundColor = "#E8FC00";

// const innerContainer = document.createElement("div");
// innerContainer.style.display = "flex";
// innerContainer.style.alignItems = "center";

// const generatedByText = document.createElement("p");
// generatedByText.textContent = "Generated By";
// generatedByText.style.marginRight = "10px";
// generatedByText.style.marginTop = "25px";
// innerContainer.appendChild(generatedByText);

// const logoImage = document.createElement("img");
// logoImage.src = "./assets/muducy-logo.png";
// logoImage.alt = "error-in-mudcy";
// logoImage.style.height = "40px";
// logoImage.style.width = "auto";
// innerContainer.appendChild(logoImage);

// footerContainer.appendChild(innerContainer);
  mainChild.append(DesktopDiv,mobile(),generateFooter());
        main.append(mainChild);
      }
}


// function Display(data){
//     console.log("data",data.Desktop.length)
//     for (let i =1; i <data.length; i++) {

//         const mainChild = document.createElement("div")
// mainChild.style.backgroundColor = "#E8FC00";
// mainChild.style.marginTop = "50px";
// mainChild.style.border = "2px solid teal";
// mainChild.style.height = "1060px";

//         // const deviceTypeMob = data[`device_type_des-${i}`];
//         const urlDes = data[`url_des-${i}`];
//         const croFeedbackDes = data[`cro_feedback_des-${i}`];

//         const DesktopDiv = document.createElement("div");
//         // DesktopDiv.style.border = "5px solid teal";
//         const header = document.createElement("div");
//         header.classList.add("main-heading");
//         // header.style.backgroundColor = "#E8FC00";
//         const h2Tag = document.createElement("h2");
//         h2Tag.textContent = `${i}. Header and main banner`;
//         header.appendChild(h2Tag);
        
  
//         const headerImageDiv = document.createElement("div");
//         headerImageDiv.classList.add("mainbanner-div");
//         const imgTag = document.createElement("img");
//         // imgTag.src = urlDes;
//         imageUrlToBase64(urlDes, base64data => {
//         // imageUrlToBase64("https://media.istockphoto.com/id/1352603244/photo/shot-of-an-unrecognizable-businessman-working-on-his-laptop-in-the-office.webp?b=1&s=612x612&w=0&k=20&c=w-p7co1-4so7fpzJI7H-ZzX-NDK1W41yKvAT_X-Z_qg=", base64data => {
//             if (base64data) {
//                 console.log(base64data)
//                 imgTag.src =base64data
//                 // imgTag.src =`data:image/jpeg;base64,/${base64data}`
//             } else {
//                 console.log('Failed to fetch and encode image.');
//             }
//         });
          
//         imgTag.alt = "error in image1";
//         headerImageDiv.appendChild(imgTag);
        
//         const desktopDesc = document.createElement("div");
//         desktopDesc.classList.add("desktopDesc-div");
//         const h3Tag = document.createElement("h3");
//         h3Tag.textContent = `${i}Heading`;
//         const pTag = document.createElement("p");
//         pTag.textContent = `${i}. ${croFeedbackDes}`;
//         desktopDesc.append(h3Tag, pTag);
//         DesktopDiv.append(header,headerImageDiv,desktopDesc);


// // Mobile
// const urlMob = data[`url_mob-${i}`];
// const croFeedbackMob = data[`cro_feedback_mob-${i}`];
//         const divMobile = document.createElement("div")
//         divMobile.classList.add("Mobile-div"); 


//         // divMobile.style.backgroundColor = "#E8FC00";
        
//         const divMobileImage = document.createElement("div")
//         divMobileImage.classList.add("Mobile-div-image"); 
        
//         const mobileImageTag = document.createElement("img")
//         imageUrlToBase64(urlMob, base64data => {
//                 if (base64data) {
//                     console.log(base64data)
//                     mobileImageTag.src = base64data
//                     // imgTag.src =`data:image/jpeg;base64,/${base64data}`
//                 } else {
//                     console.log('Failed to fetch and encode image.');
//                 }
//             });
//         // mobileImageTag.src = `${urlMob}`; 
        
//         mobileImageTag.alt = "error in mobile image"; 
//         divMobileImage.append(mobileImageTag)
        
        
//         const mobileDesc = document.createElement("div")
//         mobileDesc.classList.add("Mobile-div-desc"); 
        
//         const h3TagMob = document.createElement("h3")
//         h3TagMob.textContent = "1.Hey i am first for Mobile"
//         const pTagMob = document.createElement("p")
//         pTagMob.textContent = `${croFeedbackMob}`
        
//         mobileDesc.append(h3TagMob,pTagMob)
//         divMobile.append(divMobileImage,mobileDesc)
        


//         // ------------Powewred by mudcy-------->>>>>>
//         // Create the footer container
// const footerContainer = document.createElement("div");
// footerContainer.classList.add("footer-mudcy");
// footerContainer.style.display = "flex";
// // footerContainer.style.marginBottom = "50px";
// footerContainer.style.justifyContent = "flex-end";
// footerContainer.style.border = "2px solid";
// footerContainer.style.borderTop = "none";
// footerContainer.style.backgroundColor = "#E8FC00";

// // Create the inner container for the "Generated By" text and logo
// const innerContainer = document.createElement("div");
// innerContainer.style.display = "flex";
// innerContainer.style.alignItems = "center";

// // Create and append the "Generated By" text
// const generatedByText = document.createElement("p");
// generatedByText.textContent = "Generated By";
// generatedByText.style.marginRight = "10px";
// generatedByText.style.marginTop = "25px";
// innerContainer.appendChild(generatedByText);

// // Create and append the logo image
// const logoImage = document.createElement("img");
// logoImage.src = "./assets/muducy-logo.png";
// logoImage.alt = "error-in-mudcy";
// logoImage.style.height = "40px";
// logoImage.style.width = "auto";
// innerContainer.appendChild(logoImage);

// // Append the inner container to the footer container
// footerContainer.appendChild(innerContainer);

//   // DesktopDiv.append(header,headerImageDiv,desktopDesc);
//   mainChild.append(DesktopDiv,divMobile,footerContainer);
//         main.append(mainChild);
//       }
// }
